# Configure automatic pull and merge from google:master-with-bazel to the default, master branch, notifying CS in the unlikely event of conflicts.
version: "1"
rules:
  - base: master
    upstream: google:master-with-bazel
    mergeMethod: merge
    conflictReviewers:
      - cpsauer
